import "./globals.css"
import { roboto } from "./fonts"
import MainLayout from "@/components/MainLayout/MainLayout"
import { AuthProvider } from "./providers"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${roboto.className} overflow-hidden snap-y snap-proximity h-screen`}
			>
				<AuthProvider>
					<MainLayout>{children}</MainLayout>
				</AuthProvider>
			</body>
		</html>
	)
}
