import "./globals.css"
import { roboto } from "./fonts"
import MainLayout from "@/components/MainLayout/MainLayout"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} max-h-screen overflow-hidden`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
